# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: coverage

on:
  push:
    branches: [ "add_test_cases" ]
  pull_request:
    branches: [ "add_test_cases" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18.x'
          cache-dependency-path: go.sum
      - name: Install dependencies
        run: go get .
      - name: Run unit tests and integrated tests
        run: go test -v ./... -coverprofile="codecov.report"
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}