# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go-dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18.x'
          cache-dependency-path: go.sum
      - name: Install dependencies
        run: go get .
      - name: Build for Linux and Windows and Macos
        run: |
          cd examples/server
          go build -v -o rulego-server-linux-amd64
          GOOS=windows GOARCH=amd64 go build -v -o rulego-server-windows-amd64.exe
          GOOS=darwin GOARCH=amd64 go build -v -o rulego-server-macos-amd64
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rulego-server-binaries
          path: |
            examples/server/rulego-server-linux-amd64
            examples/server/rulego-server-windows-amd64.exe
            examples/server/rulego-server-macos-amd64
